package main

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

const modulePath = "github.com/annaselh/gorbio"

func main() {
	if len(os.Args) < 2 {
		fmt.Println("usage: modulegen <modules|extensions>")
		os.Exit(1)
	}

	target := os.Args[1]

	switch target {
	case "modules":
		if err := generateModules(); err != nil {
			fmt.Println("module generation failed:", err)
			os.Exit(1)
		}

	case "extensions":
		if err := generateExtensions(); err != nil {
			fmt.Println("extension generation failed:", err)
			os.Exit(1)
		}

	default:
		fmt.Println("unknown target:", target)
		os.Exit(1)
	}

	fmt.Println("generation successful")
}

func generateModules() error {
	entries, err := os.ReadDir(".")
	if err != nil {
		return err
	}

	var modules []string

	for _, entry := range entries {
		if !entry.IsDir() {
			continue
		}

		moduleDir := filepath.Join(".", entry.Name())

		moduleFile := filepath.Join(
			moduleDir,
			"module.go",
		)

		if _, err := os.Stat(moduleFile); err != nil {
			continue
		}

		modules = append(
			modules,
			entry.Name(),
		)
	}

	sort.Strings(modules)

	var b strings.Builder

	b.WriteString("// Code generated by modulegen; DO NOT EDIT.\n\n")
	b.WriteString("package modules\n\n")

	b.WriteString("import (\n")
	b.WriteString("\t\"github.com/annaselh/gorbio/core\"\n")

	for _, name := range modules {
		fmt.Fprintf(
			&b,
			"\t%q\n",
			modulePath+"/modules/"+name,
		)
	}

	b.WriteString(")\n\n")

	b.WriteString(
		"func RegisterAll(registry *core.Registry) error {\n\n",
	)

	for _, name := range modules {
		fmt.Fprintf(
			&b,
			"\tif err := registry.Register(%s.NewModule()); err != nil {\n",
			packageName(name),
		)

		b.WriteString("\t\treturn err\n")
		b.WriteString("\t}\n\n")
	}

	b.WriteString("\treturn nil\n")
	b.WriteString("}\n")

	return os.WriteFile(
		"registry.go",
		[]byte(b.String()),
		0644,
	)
}

func generateExtensions() error {
	entries, err := os.ReadDir(".")
	if err != nil {
		return err
	}

	var extensions []string

	for _, entry := range entries {
		if !entry.IsDir() {
			continue
		}

		extensionDir := filepath.Join(
			".",
			entry.Name(),
		)

		extensionFile := filepath.Join(
			extensionDir,
			"extension.go",
		)

		if _, err := os.Stat(extensionFile); err != nil {
			continue
		}

		extensions = append(
			extensions,
			entry.Name(),
		)
	}

	sort.Strings(extensions)

	var b strings.Builder

	b.WriteString("// Code generated by modulegen; DO NOT EDIT.\n\n")
	b.WriteString("package extensions\n\n")

	b.WriteString("import (\n")
	b.WriteString("\t\"github.com/annaselh/gorbio/core\"\n")

	for _, name := range extensions {
		fmt.Fprintf(
			&b,
			"\t%q\n",
			modulePath+"/extensions/"+name,
		)
	}

	b.WriteString(")\n\n")

	b.WriteString(
		"func RegisterAll(registry *core.ExtensionRegistry) error {\n\n",
	)

	for _, name := range extensions {
		fmt.Fprintf(
			&b,
			"\tif err := registry.Register(%s.New()); err != nil {\n",
			packageName(name),
		)

		b.WriteString("\t\treturn err\n")
		b.WriteString("\t}\n\n")
	}

	b.WriteString("\treturn nil\n")
	b.WriteString("}\n")

	return os.WriteFile(
		"registry.go",
		[]byte(b.String()),
		0644,
	)
}

func packageName(name string) string {
	var result strings.Builder

	for _, r := range name {
		if r == '-' || r == '_' {
			continue
		}

		result.WriteRune(r)
	}

	return result.String()
}
