// Code generated by modulegen; DO NOT EDIT.

package extensions

import (
	"github.com/annaselh/gorbio/core"
	"github.com/annaselh/gorbio/extensions/inventory-import"
	"github.com/annaselh/gorbio/extensions/sales-discount"
)

func RegisterAll(registry *core.ExtensionRegistry) error {

	if err := registry.Register(inventoryimport.New()); err != nil {
		return err
	}

	if err := registry.Register(salesdiscount.New()); err != nil {
		return err
	}

	return nil
}
