package core

import "time"

const (
	EnvDevelopment = "development"
	EnvProduction  = "production"
)

// Settings carries runtime configuration that modules need at request time.
// It lives on App rather than being passed to module constructors because
// modules/registry.go is generated by modulegen and calls NewModule() with no
// arguments; growing that signature would mean regenerating the wiring on every
// new setting.
type Settings struct {
	Env          string
	CookieSecure bool
	SessionTTL   time.Duration
}

// DefaultSettings fails closed: a caller that forgets to wire configuration
// still gets Secure cookies and a bounded session lifetime.
func DefaultSettings() Settings {
	return Settings{
		Env:          EnvProduction,
		CookieSecure: true,
		SessionTTL:   12 * time.Hour,
	}
}

func (s Settings) IsProduction() bool {
	return s.Env != EnvDevelopment
}
